language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: home-sweet-home-ip
  api_key:
    secure: U6BcPjVeNDQewK6CzS45BRafJXjy2QZeAiC8Oi6HQ6Xcj2FizXGCqDyrZC5QM+xMAQCtkxJVvq97zNVD2sHgI2pyvsYJrk7Mi/QaYgp+tb6WJCmRbEFPA+rpKZIUVJ5nsYpYKlXZyBcKaSHP7FbE5h0hOKijro/U+Erxj34Gk52Aio99zRe9MfbR/lnfszyD/HJT+A2r+cik38+7ELo17+X27GtXBhgJR7SLw91V5KoZIGL8gHsynLsE6l79EIuscX6uyyP6Pp7kFgaflNKySsSSJVmWMFkFF8Vc+Fn7yt0IgG0iuwFOgGzRZLSHSw61e1v4UepB9WQweyEhjgrBGQEpc6bHSf1DDjlKWoZX60iY5fKhER+7F/OxIh8nt14Q7AM6e49zp2/umwsSyxcVOdyUHTHIiGHVbr54iq0XuARXvx+4CmbmQVijYQz7wBjwb3WxrUebcetN5PuWzL3FA9zC5OFajoBcYmNSqvYSzJw8l9rAu6PbE/w+Z4ULnGDhM3/0hFF1hft8Hr+bgeEUBwYM3GCaoYSMxGDAiH0aYTZlknn+xQtx6dAV0iTYVVSyOgCflvjXQM8KGnjoJqr7H+8A1yl7Yw2UuZgzowCnwy+ltgT21nOfIxmEdgoDM0FdKTRBuxxb7zabeEPJrTtye0bqbLDP9Xk3kw5Ev0JgZak=
