language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: home-sweet-home-ip
  api_key:
    secure: gL/yEiPZkupSNHMQuWAG43/vVQD5aQeZ4hKHKMMfSpgPwFHjMmHuADwyRmJt0ZfUo5DvrLJgJwJhFFOCr1E4QYn9Lz7prDfqswFvO/Aojs3iyQtrOecSbSem1Ift1JkbjbZvUp3uL9zYYRmfG/rH4bzDM9WXkSWxsNkArWwwU80wTx6U5CAk+fbZX4GPfbLDeai1/5QG6WQkTmj00SRDEYITi780jOMQvPF5fLZWoolCzJom82soBiUEHXpfdy1T/pOIyWc6pCsafUdoB0px8+5DzSQbuWMVsmnXtWLBD6+I7LIEp82brsbNp0rHLWn9XChTuf+4IVU4Vy5oI/KI7dpT0yXPBmy+y4eBpI7FlPh6cZejNHAPnU1YniLm+s9udXk1zZTML2Y3eeR8x4wUExSW2ptP300+pxPS4MRJcvANxJOME/eRtkVbbiVgya2+5oMT97MQkM81eNYw+ZGspCs6KJUR0x2EXEqKspbFzH5uFt6kY6KSeD5h2Omdo77g7C8hNjP7CtySODvS2OPcDwSSJOdXjSN2es1fyP83J0mAMzzSUvDtxXiyPR0kS2mZ8/o8CkFZjsphDlgkw73B3Hy48mpY0DkiK2WE3VS3aORdDNT7bT+lGsC6yoWjnr+HFMaI56VZjiBwSEXuSu6bN3hSdYwhtGfVdx3/69/66wo=
